// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1686989326);
user_pref("browser.search.region", "AE");
user_pref("calendar.caldav.googleResync", 1686911327);
user_pref("calendar.list.sortOrder", "5af01fe2-3a12-4fc5-8812-8ca038035beb");
user_pref("calendar.registry.5af01fe2-3a12-4fc5-8812-8ca038035beb.calendar-main-default", true);
user_pref("calendar.registry.5af01fe2-3a12-4fc5-8812-8ca038035beb.calendar-main-in-composite", true);
user_pref("calendar.registry.5af01fe2-3a12-4fc5-8812-8ca038035beb.disabled", true);
user_pref("calendar.registry.5af01fe2-3a12-4fc5-8812-8ca038035beb.name", "Home");
user_pref("calendar.registry.5af01fe2-3a12-4fc5-8812-8ca038035beb.type", "storage");
user_pref("calendar.registry.5af01fe2-3a12-4fc5-8812-8ca038035beb.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Dubai");
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1686989325);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230503190012");
user_pref("extensions.lastAppVersion", "102.11.0");
user_pref("extensions.lastPlatformVersion", "102.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"a6903769-f1c7-4116-8e65-6dc46e587a86\",\"google@search.mozilla.org\":\"ee644c83-9e64-4f8c-af34-1e8cf770c8d7\",\"ddg@search.mozilla.org\":\"4a2eb572-e0d2-4746-99e3-13655c3d43d8\",\"amazondotcom@search.mozilla.org\":\"1cb02bc8-46e4-4e7b-a2c2-3d12de303df7\",\"wikipedia@search.mozilla.org\":\"4f551456-a74d-4e32-a57c-3c9916b3038e\",\"bing@search.mozilla.org\":\"1b6e7657-3f2d-4b64-ad06-54fef5d9f673\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "06092960-158e-4014-8f4c-f1d1ba50ea1");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "03785eea-02d3-46ea-b790-8c7479890089");
user_pref("toolkit.telemetry.previousBuildID", "20230503190012");
